# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-27 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_edited', models.DateTimeField(auto_now=True)),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='upload_files/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('post_created',),
            },
        ),
    ]
